/** Auto-generated by scripts/generate-env.mjs — do not edit manually. */
export const environment = {
  production: false,
  supabaseUrl: '',
  supabaseAnonKey: '',
  debugMode: true,
  /** Skip live Supabase I/O and persist demo data in localStorage. */
  demoMode: true,
} as const;
