/**
 * Generates src/environments/environment.ts from process.env / .env file.
 * Used locally (prestart/prebuild) and on Vercel (build step).
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const envPath = resolve(root, '.env');
const outPath = resolve(root, 'src/environments/environment.ts');

function loadDotEnv(path) {
  if (!existsSync(path)) return {};
  const lines = readFileSync(path, 'utf8').split('\n');
  const vars = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

function env(key, fallback = '') {
  return process.env[key] ?? dotenv[key] ?? fallback;
}

function envBool(key, fallback = false) {
  const raw = env(key, fallback ? 'true' : 'false').toLowerCase();
  return raw === 'true' || raw === '1';
}

const dotenv = loadDotEnv(envPath);
const templatePath = resolve(root, 'src/environments/environment_template.ts');

// Preserve gitignored environment.ts when developer manages secrets manually.
if (existsSync(outPath) && !envBool('FORCE_ENV_GENERATE', false)) {
  console.log('[generate-env] Skipped — environment.ts exists (set FORCE_ENV_GENERATE=true to overwrite).');
  process.exit(0);
}

const hasCiEnv =
  Boolean(env('NG_APP_SUPABASE_URL')) ||
  Boolean(env('NG_APP_SUPABASE_ANON_KEY'));

if (!hasCiEnv && !envBool('FORCE_ENV_GENERATE', false) && existsSync(templatePath)) {
  const template = readFileSync(templatePath, 'utf8');
  writeFileSync(outPath, template, 'utf8');
  console.log('[generate-env] Created environment.ts from environment_template.ts');
  process.exit(0);
}

const content = `/** Auto-generated by scripts/generate-env.mjs — do not edit manually. */
export const environment = {
  production: ${envBool('NG_APP_PRODUCTION', false)},
  supabaseUrl: '${env('NG_APP_SUPABASE_URL', '')}',
  supabaseAnonKey: '${env('NG_APP_SUPABASE_ANON_KEY', '')}',
  debugMode: ${envBool('NG_APP_DEBUG_MODE', true)},
  demoMode: ${envBool('NG_APP_DEMO_MODE', true)},
} as const;
`;

writeFileSync(outPath, content, 'utf8');
console.log('[generate-env] Wrote', outPath);
