import { Component, input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { InsightItem } from '@core/interfaces/ISaleRecordDto.interface';

@Component({
  selector: 'app-insight-card',
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (isRecommendation()) {
      <div class="recommendation-item" role="listitem">
        <span class="rec-icon" aria-hidden="true">{{ item().icon }}</span>
        <div class="rec-content flex-column gap-s">
          <span class="rec-title">{{ item().title }}</span>
          <!-- parseBold returns HTML with <strong> tags for bold text -->
          <p class="rec-body" [innerHTML]="parseBold(item().body)"></p>
        </div>
      </div>
    } @else {
      <div class="insight-card insight-card--{{ item().severity }}" role="article">
        <div class="insight-card-header">
          <span class="insight-icon" aria-hidden="true">{{ item().icon }}</span>
          <span class="insight-title">{{ item().title }}</span>
          <span class="insight-severity-dot dot--{{ item().severity }}" [attr.aria-label]="'Severity: ' + item().severity"></span>
        </div>
        <!-- parseBold returns HTML with <strong> tags for bold text -->
        <p class="insight-body" [innerHTML]="parseBold(item().body)"></p>
      </div>
    }
  `,
  styleUrl: './insight-card.component.css'
})
export class InsightCardComponent {
  item = input.required<InsightItem>();
  isRecommendation = input(false);

  parseBold(text: string): string {
    if (!text) return '';
    // Security: item.body is generated by SalesProcessingService and is trusted internally.
    return text.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  }
}
